In [ ]:
import torch
t,c = torch.__version__.split('+')
print(f'Pytorch version:{t} \n Cuda Version: {c}')

Pytorch version:2.6.0
 Cuda Version: cu124

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.tensor

In [ ]:
x = torch.tensor(4 , dtype=torch.float32 , device='cuda' , requires_grad=True)

In [ ]:
y = x**2

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(8., device='cuda:0')

# Training my First Neural Network (Accuracy doesnt matter)

In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

In [2]:
#Libraries
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.metrics import accuracy_score

In [3]:
#read csv
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id' , 'Unnamed: 32'] , inplace=True)

In [5]:
df.keys()

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [6]:
df.shape

(569, 31)

In [7]:
set(df['diagnosis'])

{'B', 'M'}

In [8]:
all_features = df.iloc[: , 1:]      #all rows , 1st index column to last index (skipping 0th index)
target_variables = df.iloc[: , 0]  #all rows , 0th index column only
X_train , X_test , Y_train , Y_test = train_test_split(all_features , target_variables , test_size=0.3)

In [9]:
#standardizing input features
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [10]:
X_train.shape
X_test_scaled.shape

(171, 30)

In [11]:
Y_test

205    M
320    B
195    B
117    M
268    B
      ..
204    B
74     B
445    B
368    M
122    M
Name: diagnosis, Length: 171, dtype: object

In [12]:
#changing the categorical variables into numeric variables
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test_encoded = encoder.transform(Y_test)

In [13]:
Y_train

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1])

In [14]:
# Converting arrays to tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test_scaled)
Y_train_tensor = torch.from_numpy(Y_train)
Y_test_tensor = torch.from_numpy(Y_test_encoded)

In [15]:
X_train_tensor.shape

torch.Size([398, 30])

In [33]:
#Neural Network (1 neuron)
class neuralnetwork():
  def __init__(self,X):
    '''
    Weights and Biases
    Since each feature has a single weight, we only need x.size number of rows & just a single column
    Since we are creating a network with a single neuron, we will only have a single bias only aswell
    '''
    self.weights = torch.rand(size=(X.size()[1], 1) ,dtype=X.dtype, requires_grad=True)#initializing random weights (1 weight for each feature)
    self.biases = torch.zeros(size=(1,),dtype=X.dtype, requires_grad=True)   #bias will start from 0

  def forward_pass(self, X):
    '''
    We need to perform a matrix multiplication between the incoming features and the weights and then add the bias terms
    '''
    #Multiplication and Addition
    Z = torch.matmul(X,self.weights) + self.biases   # (featuresMatrix * WeightsMatrix) + biasesMatrix
    #Activation Function
    ypred = torch.sigmoid(Z)
    return ypred    #the size of this tensor would be the same as the size of the original Y column (thus helping in calculation of loss)

  def calculate_loss(self,y_predicted,y_original):
    '''
    Calculating the loss value in order to check how far predicted output is from the original
    Predicted output would be the ypred calculated in the forward pass
    e.g Binary cross entropy loss
    '''
    epsilon = 1e-7
    y_predicted = torch.clamp(y_predicted, epsilon, 1 - epsilon)
    return torch.nn.functional.binary_cross_entropy(y_predicted , y_original)

In [34]:
model = neuralnetwork(X_train_tensor)

In [35]:
#variables
epochs = 30
learningRate = 0.1
resized_Y_train_tensor = Y_train_tensor.view([-1,1]).double()   #resizing the tensor to look like the prediction tensor and chaing its dtype to be same as the preicted tensor aswell
#loop for training the network
for counter in range(epochs):
  #forward pass
  y_pred = model.forward_pass(X_train_tensor)
  #calculate loss
  loss = model.calculate_loss(y_pred , resized_Y_train_tensor)
  print(f"Epoch: {counter+1} , Loss: {loss.item()}")
  #backward prop
  loss.backward()    #autograd calculates the gradient descent
  #update the weights and biases manually
  with torch.no_grad():   #have to turn off gradient tracking when auto updating weights and biases
    model.weights.data -= learningRate*model.weights.grad
    model.biases.data -= learningRate*model.biases.grad
  #we want the gradients to be calculated from fresh each time in each iteration
  model.weights.grad.zero_()
  model.biases.grad.zero_()

Epoch: 1 , Loss: 0.5280988604528729
Epoch: 2 , Loss: 0.5174661405638564
Epoch: 3 , Loss: 0.5071355940590322
Epoch: 4 , Loss: 0.4971030867430009
Epoch: 5 , Loss: 0.4873633678965752
Epoch: 6 , Loss: 0.47790951027683215
Epoch: 7 , Loss: 0.4687326447872789
Epoch: 8 , Loss: 0.45982204725354275
Epoch: 9 , Loss: 0.45116554001226916
Epoch: 10 , Loss: 0.442750094345468
Epoch: 11 , Loss: 0.43456249062372193
Epoch: 12 , Loss: 0.4265899138052036
Epoch: 13 , Loss: 0.418820410628759
Epoch: 14 , Loss: 0.4112431854467073
Epoch: 15 , Loss: 0.40384874881345084
Epoch: 16 , Loss: 0.3966289511640029
Epoch: 17 , Loss: 0.3895769372813638
Epoch: 18 , Loss: 0.382687052415686
Epoch: 19 , Loss: 0.37595472247866074
Epoch: 20 , Loss: 0.3693763225533779
Epoch: 21 , Loss: 0.362949041554912
Epoch: 22 , Loss: 0.356670746782683
Epoch: 23 , Loss: 0.35053985018751505
Epoch: 24 , Loss: 0.3445551779650471
Epoch: 25 , Loss: 0.33829909951847237
Epoch: 26 , Loss: 0.3313596845350895
Epoch: 27 , Loss: 0.324590786719045
Epoch: 28 , Loss: 0.31799204268536635
Epoch: 29 , Loss: 0.31156302938546787
Epoch: 30 , Loss: 0.30530321827841606

In [36]:
model.biases

tensor([-0.0634], dtype=torch.float64, requires_grad=True)

In [64]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.543380856513977

# Creating the same network using nn.Module

In [16]:
from torch import nn
from torch.optim import SGD
class upgradedNeuralNetwork(nn.Module):
  def __init__(self, input_features):
    #initializing the parent constructor
    super().__init__()
    #Creating the input layer having single neuron as first
    self.firstlayer = nn.Linear(input_features , 1)     #the input features are the inputs going into each neuron, the second argument is the number of neurons in this layer
                                                        #the number of outputs from this layer is equivalent to number of neurons
  def forward(self , X):
    #performing the matmul step thorugh the nn.Linear function
    Z = self.firstlayer(X)
    y_pred = torch.sigmoid(Z)
    return y_pred

  def loss(self,y_prediction , y_original):
    return torch.nn.BCELoss()(y_prediction , y_original)

In [18]:
#variables
input_features = X_train_tensor.size()[1]

model = upgradedNeuralNetwork(input_features)
epochs = 30
learningrate = 0.01
optimizer = SGD(params=model.parameters() , lr=learningrate)

for counter in range(epochs):
  optimizer.zero_grad()   #reset the gradients
  y_pred = model(X_train_tensor.to(dtype=torch.float32))    #forward pass
  loss = model.loss(y_pred , Y_train_tensor.view([-1,1]).to(dtype=torch.float32))   #calculate the loss value
  print(f"Epochs: {counter+1} , Loss: {loss.item()}")

  loss.backward()     #calculate the new gradients
  optimizer.step()    #updates the weights

Epochs: 1 , Loss: 0.48897501826286316
Epochs: 2 , Loss: 0.48073533177375793
Epochs: 3 , Loss: 0.4728681743144989
Epochs: 4 , Loss: 0.46534913778305054
Epochs: 5 , Loss: 0.45815572142601013
Epochs: 6 , Loss: 0.45126718282699585
Epochs: 7 , Loss: 0.4446644186973572
Epochs: 8 , Loss: 0.4383299946784973
Epochs: 9 , Loss: 0.4322475790977478
Epochs: 10 , Loss: 0.4264022707939148
Epochs: 11 , Loss: 0.420780211687088
Epochs: 12 , Loss: 0.41536855697631836
Epochs: 13 , Loss: 0.4101555645465851
Epochs: 14 , Loss: 0.405129998922348
Epochs: 15 , Loss: 0.4002818465232849
Epochs: 16 , Loss: 0.3956015110015869
Epochs: 17 , Loss: 0.39108017086982727
Epochs: 18 , Loss: 0.3867095410823822
Epochs: 19 , Loss: 0.38248199224472046
Epochs: 20 , Loss: 0.37839028239250183
Epochs: 21 , Loss: 0.37442779541015625
Epochs: 22 , Loss: 0.37058815360069275
Epochs: 23 , Loss: 0.3668655753135681
Epochs: 24 , Loss: 0.3632543981075287
Epochs: 25 , Loss: 0.3597496747970581
Epochs: 26 , Loss: 0.3563464283943176
Epochs: 27 , Loss: 0.35304009914398193
Epochs: 28 , Loss: 0.3498263657093048
Epochs: 29 , Loss: 0.34670132398605347
Epochs: 30 , Loss: 0.34366098046302795

In [21]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.to(dtype=torch.float32))
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.619267463684082